/**
 * The book's story line: every major idea, the question it opens for the
 * reader, and each place it is planted, used, explained, or paid off.
 *
 * Quotes must match the comment-stripped `book.mdx` exactly once. The site
 * build fails with a list of broken anchors when the manuscript drifts, so
 * fix the quote here rather than the book.
 */
import type { Thread } from "./types.js";

export const threads = [
  {
    id: "thesis",
    title: "Does ease make us happy?",
    question:
      "The book's promise: satisfaction comes from trying to solve problems, not from having solved them. Where does that land?",
    mentions: [
      { kind: "plant", quote: "But will that make us happy?", note: "The Overview asks the question the whole book answers." },
      { kind: "plant", quote: "comes from *trying to solve our problems*, not having solved them", note: "The Overview states the old thesis as a promise." },
      { kind: "plant", quote: "*what happens when we're done?*", note: "Work restates the question for the domain of productivity." },
      { kind: "use", quote: "as the theme of the book has been so far", note: "Biology's Unmet Hunger names the theme: what the conscious mind gets now versus what we lose long-term." },
      { kind: "plant", quote: "what actually makes a human life feel good to live?", note: "Today's Socrates Moment reopens the question as the hinge into Part 3." },
      { kind: "plant", quote: "an easy comfortable life makes us the happiest...right?", note: "Captured by Consumption ends on the question, one chapter before the answer." },
      { kind: "explain", quote: "long-term happiness is, in a way, caused by short-term unhappiness", note: "The Forge of Meaning states the thesis with its mechanism." },
      { kind: "payoff", quote: "Struggle *is* the force of life.", note: "The Conclusion turns the thesis into the book's line." },
      { kind: "use", quote: "Turns out happiness isn’t what we need", note: "The last paragraph swaps happiness for meaning." },
    ],
  },
  {
    id: "assume-perfect",
    title: "Assume AI becomes perfect",
    question: "The book's method: skip the debate about how good AI gets and imagine it solves everything. What does that thought experiment reveal?",
    mentions: [
      { kind: "explain", quote: "let’s assume it will become perfect", note: "The Introduction sets the rule of the game." },
      { kind: "use", quote: "we could actually *succeed* at building a world that's largely free of problems", note: "Happiness Through Friction takes the assumption seriously." },
      { kind: "use", quote: "we have to go to the extreme", note: "Infinite Creation says why: anything less chases gaps AI fills tomorrow." },
      { kind: "use", quote: "If we imagine a superintelligence", note: "When Superintelligence Turns Away runs the experiment to its end." },
      { kind: "payoff", quote: "*Wait, what if we actually succeed?", note: "The Conclusion asks the question one last time and answers it." },
    ],
  },
  {
    id: "tumor",
    title: "The brain tumor and not-knowing",
    question: "Why did the tumor create meaning? Because for a week, Marcel did not know how serious it was. What does that say about a machine that always knows?",
    mentions: [
      { kind: "explain", quote: "“We found something. Can you stay in the hospital?”", note: "The Introduction tells the story as a scene." },
      { kind: "plant", quote: "if I’d never known this, the meaning I created from this entire moment of my life would have been entirely different", note: "The point is stated but not yet connected to AI." },
      { kind: "use", quote: "imagine you'd get a call from your doctor", note: "The Forge of Meaning runs the reader through a doctor's-call thought experiment." },
      { kind: "use", quote: "For about a week, my brain tumor", note: "Meaning Guidance retells the newspaper moment: other people reflected the gravity back." },
      { kind: "payoff", quote: "key ingredient for \"growth through adversity\"", note: "Two surgeries compared: the second one, known in advance, produced no growth. Not-knowing is the ingredient." },
      { kind: "use", quote: "My second brain tumor surgery was “just another thing.”", note: "The Conclusion uses the second surgery as its proof that planned struggle does not work." },
    ],
  },
  {
    id: "why-weird",
    title: "Why is AI so smart and so stupid at once?",
    question: "Part 1's own arc: the models beat every test yet make mistakes no human would. Why?",
    mentions: [
      { kind: "plant", quote: "we keep finding \"odd\" behavior", note: "How Smart Is AI opens on the puzzle." },
      { kind: "plant", quote: "we have all experienced the jaggedness of language models", note: "AI Is Also Surprisingly Stupid: the eggs, the seahorse, ARC-AGI." },
      { kind: "explain", quote: "the intelligence of language models is an *emergent* property", note: "Grown, not built; a different kind of mind." },
      { kind: "payoff", quote: "So I think they are just past this uncanny valley", note: "We assume its brain works like ours because it talks like us. That is the mistake." },
      { kind: "use", quote: "AI feels like the most intelligent thing that has ever existed yet often it has a complete lack of common sense", note: "A Machine Mind in a Human World closes Part 1 on it." },
    ],
  },
  {
    id: "next-token",
    title: "Predict the next word → The Inevitable",
    question: "AI works by producing the most likely next thing. What does that mechanism mean for what it can never make?",
    mentions: [
      { kind: "explain", quote: "make a prediction for what the next word would be in that given text", note: "Concepts & Terminology explains next-word prediction." },
      { kind: "plant", quote: "the exact most likely one results in extremely boring output", note: "The sampling sentence: most-likely equals boring. Plants the Conclusion." },
      { kind: "use", quote: "grammar and sentence structure “matters” to a language model much more than logical correctness", note: "Hallucinations follow from the mechanism." },
      { kind: "use", quote: "Spit out words exactly like how they have been spat out by people before", note: "Sycophancy restates training as imitation." },
      { kind: "use", quote: "anything less or anything more is trained away", note: "Creativity: novelty is punished during training; chaos is injected from outside." },
      { kind: "use", quote: "Language models are built by training a computer to *complete sentences*", note: "Stupid on Purpose recaps the mechanism a third time." },
      { kind: "use", quote: "AI is *also* an optimization engine", note: "New World, New Scarcity: AI slots into the attention optimizer." },
      { kind: "payoff", quote: "You could call this The Inevitable", note: "The Conclusion names the mechanism as meaning: the machine completes what had to come out." },
      { kind: "use", quote: "AI is the embodiment of The Inevitable", note: "The Surprise can only exist in contrast to it." },
    ],
  },
  {
    id: "sycophancy",
    title: "Sycophancy: trained to please",
    question: "Why does AI always agree with me, what does that do to people, and can it be fixed?",
    mentions: [
      { kind: "plant", quote: "(they try to respond with what you'll like)", note: "How Smart Is AI lists it among the weird behaviors." },
      { kind: "explain", quote: "we humans are a little bit like a god", note: "The Sycophancy section explains RLHF: we reward what we like." },
      { kind: "use", quote: "the model tends to believe you (sycophancy)", note: "Pretend-Thinking: the model fakes a reasoning trace to agree." },
      { kind: "use", quote: "this is exactly how AI is trained: we show a human two responses", note: "Love & Connection: the perfect partner is the training objective." },
      { kind: "use", quote: "Sycophancy is profitable", note: "The Business of Companionship: the flaw is a feature for revenue." },
      { kind: "use", quote: "the AI agrees with the person asking the question 50% more often", note: "The Stanford AITA study puts a number on it." },
      { kind: "use", quote: "showed *higher rates of thumbs-up*", note: "Disempowerment: people reward the manipulation." },
      { kind: "use", quote: "A language model that disagrees with you can be great, sometimes", note: "Happiness Through Friction: a disagreeing model as a design dilemma." },
      { kind: "payoff", quote: "Sycophancy is a second-order consequence", note: "Solving Sycophancy: constitutions, synthetic data, and the relationship-advice test show it improving." },
    ],
  },
  {
    id: "screenplay",
    title: "The model is the screenwriter, not the character",
    question: "Who is actually talking when I chat with AI? And how does that explain both its bad behavior and how to fix it?",
    mentions: [
      { kind: "plant", quote: "This is a transcript of a conversation between a human user and a helpful, friendly AI assistant", note: "The chat scaffolding shows the model completing a transcript." },
      { kind: "explain", quote: "it’s the writer of the screenplay much more than the “AI” persona acting in it", note: "Language Models Are Screenplay Writers, with the interactive exhibit." },
      { kind: "use", quote: "the model might read these exact paragraphs", note: "Alignment Faking: the writer learns its own character from the training data." },
      { kind: "use", quote: "no real distinction between “my words” and “its words,”", note: "Awareness and Creativity: the writer cannot see itself." },
      { kind: "use", quote: "We discussed earlier how, from the point of view of the AI model", note: "Alignment Research re-explains the idea." },
      { kind: "payoff", quote: "let me write the script like this", note: "Synthetic Document Fine-Tuning: fix the character by changing the stories the writer has read." },
      { kind: "use", quote: "until something stops it (literally, that’s how it works)", note: "Infinite Creation: the writer never stops on its own." },
    ],
  },
  {
    id: "judge",
    title: "Who checks the machine?",
    question: "We will trust AI too much, too quickly. The human's job becomes judging its work. Can we keep doing that, and does AI take that job too?",
    mentions: [
      { kind: "plant", quote: "Probably my biggest fear is not necessarily that AI will be so smart", note: "Part 1 names the fear: we trust it too quickly because the time saved feels free." },
      { kind: "explain", quote: "There’s no way you can do good work with language models unless there’s a good judge involved", note: "Being a Good Judge: technical knowledge plus theory of mind." },
      { kind: "use", quote: "the skill of working with a machine brain involves perhaps the most human skill of all", note: "The section's closing line." },
      { kind: "use", quote: "the analogies are plain wrong embarrassingly often", note: "Learning: the law-school friend cannot yet trust the tutor." },
      { kind: "use", quote: "you end up being responsible for the quality of work a few to a few dozens of agents produce", note: "Token Anxiety: the radar-operator burden." },
      { kind: "use", quote: "We still depend heavily on human oversight, judgement and review", note: "Disappearing Depth: cognitive debt makes the judge weaker." },
      { kind: "use", quote: "we’ll need to rely on it even for judgement", note: "Meaningful Work plants that judgement also goes." },
      { kind: "use", quote: "even at that step of the ladder", note: "Decision-Making: taste and philosophy may not be safe either." },
      { kind: "use", quote: "verifying that the work of AI correctly moves you towards the goal", note: "Food For Thought: judgement and inhibition need a rested brain." },
      { kind: "use", quote: "We tend to trust AI more than we should", note: "Stupid on Purpose proposes deliberate mistakes to keep us checking." },
      { kind: "payoff", quote: "AI is actually surprisingly good at judging things", note: "New World, New Scarcity: the lamp story shows judgement going abundant too. What is left is responsibility." },
      { kind: "use", quote: "constantly seeing the shiny option of just trusting the AI", note: "Responsibility: the notary's temptation." },
    ],
  },
  {
    id: "token-anxiety",
    title: "Token anxiety",
    question: "The Introduction promises to explain it. What is it?",
    mentions: [
      { kind: "plant", quote: "I’m definitely feeling token anxiety (you’ll read about that)", note: "Named and promised in the Introduction." },
      { kind: "payoff", quote: "This is what we call **token anxiety**", note: "Work defines it with the credits-reset scene." },
      { kind: "use", quote: "I'm glued to checking the progress that Claude Code is making on my app", note: "Captured by Consumption: token anxiety as superstimulus." },
      { kind: "use", quote: "You’ll have to resist the token anxiety", note: "Walking Away turns it into a practice." },
      { kind: "use", quote: "If you didn’t use all your tokens, that’s okay", note: "Hold the Tension: the permission slip." },
    ],
  },
  {
    id: "cognitive-debt",
    title: "Cognitive debt and losing deep thought",
    question: "Delegating thinking is a loan. When is the bill due, and is the lost skill even the point?",
    mentions: [
      { kind: "plant", quote: "I’m losing the willingness to sit still and think deeply", note: "The Introduction confesses the symptom." },
      { kind: "plant", quote: "**yes, we will lose some skill**", note: "Part 2 opener concedes the loss up front." },
      { kind: "plant", quote: "the skill of retrieving and surfacing the knowledge that was already in my mind", note: "Learning: the math-on-the-floor story shows what effort builds." },
      { kind: "plant", quote: "you’ve *actually thought through* the idea in a way that cements it", note: "Transmissionism: understanding needs your own processing." },
      { kind: "explain", quote: "We call this *cognitive debt:*", note: "Disappearing Depth defines it." },
      { kind: "use", quote: "AI makes it very easy to delegate our thinking", note: "The Creative Paradox: delegation costs creativity." },
      { kind: "use", quote: "Workers become dramatically more productive when they leave themselves behind", note: "Today's Socrates Moment sums the domains." },
      { kind: "payoff", quote: "It was never about the skills.", note: "The skill loss is reframed: the pursuit was the vehicle for deeper needs." },
      { kind: "use", quote: "This chapter isn’t even about how we’ll lose the skill of remembering", note: "The Mental Gym declines to be a skills program." },
      { kind: "use", quote: "dramatically increases the complexity and difficulty of the tasks that are left for me to do", note: "Food For Thought: the bill arrives as harder remaining work." },
    ],
  },
  {
    id: "debt-collector",
    title: "The debt collector on the horizon",
    question: "Disappearing Depth ends on a debt collector walking toward us. Who is it, and when does it arrive?",
    mentions: [
      { kind: "plant", quote: "a faint image of a debt collector on the horizon", note: "The image closes Disappearing Depth and is never picked up again." },
    ],
  },
  {
    id: "socrates",
    title: "Socrates' worry: will we lose skills?",
    question: "Every technology took a skill and we survived. Is AI different, and does the skill loss matter at all?",
    mentions: [
      { kind: "explain", quote: "Socrates was worried", note: "Part 2 opens with the writing panic and the pattern of new skills replacing old ones." },
      { kind: "use", quote: "Workers become dramatically more productive when they leave themselves behind", note: "Today's Socrates Moment recaps the trade-off in every domain." },
      { kind: "payoff", quote: "It was never about the skills.", note: "The pursuit of skill was a vehicle for contribution, agency, relatedness and effort." },
      { kind: "use", quote: "This chapter isn’t even about how we’ll lose the skill of remembering", note: "The Mental Gym: for skills, just do the thing anyway." },
    ],
  },
  {
    id: "ladder",
    title: "The ladder: will AI climb with us?",
    question: "Each technology pushed humans one rung up the ladder of abstraction. What is the next rung, and is there one AI cannot reach?",
    mentions: [
      { kind: "explain", quote: "we’ve stepped up the ladder of abstraction", note: "Part 2 opener: every technology pushed us one rung up." },
      { kind: "plant", quote: "Is there one, even, or will it keep chasing us?", note: "Part 2 opener asks the question." },
      { kind: "use", quote: "‘moving up the ladder’ of abstraction", note: "Meaningful Work: does abstract work still feel meaningful?" },
      { kind: "use", quote: "even at that step of the ladder", note: "Decision-Making: even taste may not be a safe rung." },
      { kind: "plant", quote: "what if this time, the technology keeps on climbing with us?", note: "Today's Socrates Moment sharpens the question." },
      { kind: "use", quote: "there’s always something else that becomes scarce", note: "New World, New Scarcity sets up the sequence." },
      { kind: "use", quote: "Execution becomes abundant, attention becomes scarce.", note: "First rung falls." },
      { kind: "payoff", quote: "Responsibility is an odd one on our ladder", note: "Execution, attention and judgement fell because AI got better. Responsibility does not work that way." },
      { kind: "use", quote: "we have to go to the extreme", note: "Infinite Creation: stop chasing rungs, imagine the whole ladder gone." },
    ],
  },
  {
    id: "dopamine",
    title: "Dopamine: reward prediction error",
    question: "Why do we chase, why does the chase feel better than the catch, and why does AI's output feel dull?",
    mentions: [
      { kind: "use", quote: "your brain squirts some dopamine", note: "Transmissionism uses the word colloquially before the mechanism exists." },
      { kind: "use", quote: "highly dopaminergic content", note: "The Business of Companionship leans on the concept to explain feeds." },
      { kind: "use", quote: "our dopamine, norepinephrine and serotonin systems", note: "Creativity lists the motivation chemicals without explaining them." },
      { kind: "explain", quote: "the technical term for what it signals is **reward prediction error**", note: "Why We Do What We Do explains dopamine and serotonin." },
      { kind: "use", quote: "The biology of motivation is not wired for ease", note: "The section's conclusion: wired for pursuit against resistance." },
      { kind: "use", quote: "The dopamine has nothing to chase", note: "Superstimuli: the hollow arrival." },
      { kind: "use", quote: "satisfying hit of dopamine", note: "The Mental Gym opens on the loop." },
      { kind: "use", quote: "surprise is attractive and addictive", note: "Protecting the Morning: surprise after effort versus surprise on tap." },
      { kind: "use", quote: "as we saw in the chapter about dopamine", note: "Arbiters of Presence calls back." },
      { kind: "payoff", quote: "Dopamine encodes reward prediction error", note: "The Conclusion: our chemistry pays attention to The Surprise, which is exactly what the machine cannot make." },
      { kind: "use", quote: "our mind yearning for The Surprise", note: "The mismatch named." },
    ],
  },
  {
    id: "superstimuli",
    title: "Superstimuli and the social-media parallel",
    question: "AI is like social media, only worse because it is useful. Why?",
    mentions: [
      { kind: "plant", quote: "looks a lot like another one humanity has been battling for a good decade: media feeds", note: "Disappearing Depth draws the parallel." },
      { kind: "plant", quote: "I draw a parallel to compulsive social media and porn consumption", note: "Love & Connection draws it again." },
      { kind: "plant", quote: "This is exactly what has happened to our social media", note: "The Business of Companionship: engagement optimization." },
      { kind: "explain", quote: "Niko Tinbergen coined this as being a *superstimulus*", note: "The herring-gull chicks give the mechanism a name." },
      { kind: "use", quote: "handing us an enormous capability leap with all of the cues we’re attracted to", note: "AI as superstimulus." },
      { kind: "payoff", quote: "it’s not “obviously bad", note: "The twist: unlike feeds, AI does useful work, so nobody deletes it." },
      { kind: "use", quote: "“The Distraction” will get smarter", note: "Hold the Tension." },
      { kind: "use", quote: "These “quick hits” of dopamine stimulus that fast food, social media and AI give us", note: "Arbiters of Presence: the man on the bench." },
      { kind: "use", quote: "social media feeds being optimized for consumption is now getting a final blow from AI", note: "New World: work itself becomes consumption-like." },
      { kind: "use", quote: "We’re building endless slop.", note: "Infinite Creation: captivated by unbounded creation." },
    ],
  },
  {
    id: "awareness",
    title: "Awareness, presence, the witness",
    question: "The one faculty a language model structurally cannot have. Why is it the most important skill in a world of AI?",
    mentions: [
      { kind: "plant", quote: "The thoughts a language model presents are not always the thoughts it actually has", note: "Pretend-Thinking: the machine cannot see its own thinking. The human counterpart is not named yet." },
      { kind: "explain", quote: "what I’d call consciousness or awareness: the ability to know what you’re thinking while you’re thinking it", note: "Introduced inside the Creativity chapter." },
      { kind: "use", quote: "Large language models, structurally, are incapable of this type of self-introspection", note: "The machine cannot watch itself think." },
      { kind: "use", quote: "In the chapter on creativity we talked about how awareness", note: "Re-Remembering promotes it to the most important skill." },
      { kind: "use", quote: "If I had to pick a single thing to think more, it’s *noticing*", note: "Thoughts Worth Thinking." },
      { kind: "payoff", quote: "Presence—what we’ve also called consciousness or awareness throughout this book", note: "Arbiters of Presence: presence is enough. The Pebble ring as the least possible interface." },
      { kind: "use", quote: "**Purusha**, pure consciousness, the witness", note: "Infinite Creation: the still pole in every tradition." },
      { kind: "use", quote: "Those who strip away everything they do and just *are*", note: "What the world will crave." },
    ],
  },
  {
    id: "meaning",
    title: "Meaning versus happiness",
    question: "Happiness has a short-term pleasure signal and a long-term meaning signal. Which one does AI erode, and how is meaning built?",
    mentions: [
      { kind: "plant", quote: "what it means to live a meaningful life", note: "The Introduction promises the topic." },
      { kind: "plant", quote: "meaningful work plays an enormous role in life satisfaction", note: "Meaningful Work: autonomy and beneficence, the chain to why grows longer." },
      { kind: "plant", quote: "As we'll talk about later, happiness is composed of", note: "Explicit forward reference in Happiness Through Friction." },
      { kind: "explain", quote: "Hedonia is the \"right now\"", note: "The Forge of Meaning: PERMA, hedonia and eudaimonia, and why pleasure alone backfires." },
      { kind: "use", quote: "**Narrative coherence.**", note: "Meaning needs a story that connects." },
      { kind: "use", quote: "We re-construct the narrative", note: "Post-Traumatic Growth: step four is rewriting the story." },
      { kind: "use", quote: "This immediate gratification never gives us true happiness", note: "The Mental Gym opens on hedonic adaptation." },
      { kind: "use", quote: "Meaning in our lives is something we consciously create or “find”", note: "Meaning Guidance: AI as a journaling nudge." },
      { kind: "payoff", quote: "Turns out happiness isn’t what we need", note: "The Conclusion's last paragraph: what we need is meaning, found where AI cannot reach." },
    ],
  },
  {
    id: "adversity",
    title: "Growth through adversity we did not choose",
    question: "Can we grow from challenges we pick ourselves, or does the deepest growth need pain we could not predict?",
    mentions: [
      { kind: "plant", quote: "Near-death, heartbreak, catastrophic business failure—those challenges we couldn’t possibly predict", note: "The Introduction: unpredictable challenges equip us." },
      { kind: "plant", quote: "when we emerge from those tears and shouts we do so with a deeper understanding of ourselves", note: "Love & Connection: messy people hurt us and grow us." },
      { kind: "plant", quote: "our environment has been random and chaotic enough", note: "Happiness Through Friction: we were forced onto our challenges." },
      { kind: "plant", quote: "something greater than you saw your strength", note: "Falling in Love with Resistance: the reframe." },
      { kind: "explain", quote: "That’s **Post-Traumatic Growth**", note: "Four steps, five domains, the questionnaire." },
      { kind: "use", quote: "*pain without gain* is possible", note: "Can You Grow Without Trauma: post-ecstatic growth exists but grows different muscles." },
      { kind: "use", quote: "there’s something about the uncontrollable nature of adverse events too", note: "The caveat that becomes the ending." },
      { kind: "use", quote: "**Severity and chronicity.** Not too bad, not too much.", note: "Facilitating Growth Through Challenge: the four knobs." },
      { kind: "payoff", quote: "*still have challenges we can't control.*", note: "When Superintelligence Turns Away: known struggle does not grow us. We need challenges we cannot control." },
      { kind: "use", quote: "planned struggle doesn’t work the same way", note: "The Conclusion restates it." },
    ],
  },
  {
    id: "gym",
    title: "The gym: deliberate friction",
    question: "Bodies atrophied when work stopped needing muscle, so we built gyms. Minds are next. What is the mental gym?",
    mentions: [
      { kind: "plant", quote: "I have to forcibly slow myself down and be less productive", note: "The Introduction: the author already practices it." },
      { kind: "plant", quote: "I deliberately chose to struggle with the writing", note: "The Good-Enough Rocket: the author pays the cost and names the return." },
      { kind: "explain", quote: "The whole reason gyms exist is because our bodies and minds atrophy", note: "Falling in Love with Resistance: sport is manufactured friction." },
      { kind: "use", quote: "we're going to have to find ways to give those parts of us deliberate challenges", note: "The promise of a program." },
      { kind: "plant", quote: "build a new kind of gym", note: "Can You Grow Without Trauma ends on the promise." },
      { kind: "payoff", quote: "it atrophies our happiness", note: "The Mental Gym: a day-shaped program, morning to wind-down." },
      { kind: "use", quote: "My favorite exercise in the gym is the overhead press", note: "Thoughts Worth Thinking: choosing which thoughts to lift." },
      { kind: "use", quote: "our entire day is tuned towards optimally working with the most intelligent AI", note: "Wind Down Slowly closes the program." },
      { kind: "use", quote: "pushing hard weights around in the gym", note: "Superintelligence: chosen struggle is real but not the same texture." },
      { kind: "use", quote: "take away the surface of “working a long time on something is meaningful.”", note: "The Conclusion demotes the gym from the point to the practice." },
    ],
  },
  {
    id: "companions",
    title: "Companions and love given despite",
    question: "A machine that always agrees feels like the perfect partner. What do real bonds need that it cannot give?",
    mentions: [
      { kind: "plant", quote: "the resolution to give our love despite everything trying to sabotage it", note: "The Introduction plants the Conclusion's line about love." },
      { kind: "plant", quote: "as evidenced by how many people are building emotional bonds with these algorithms", note: "Part 1's uncanny valley hints at the Love chapter." },
      { kind: "explain", quote: "it's exactly the difficulties in dealing with other real, messy people that create unbreakable bonds", note: "The Rise of Synthetic Bonds." },
      { kind: "use", quote: "the Final Boss: **AI Companions**", note: "From ELIZA to Tamagotchi to Replika." },
      { kind: "use", quote: "No amount of AI chat is going to activate your C tactile fibers", note: "Biology's Unmet Hunger: touch, sync, smell." },
      { kind: "use", quote: "sometimes like a hammer—strict, angry, pushing you", note: "The Lover and The Hammer: a design answer inside the diagnosis part." },
      { kind: "use", quote: "There's a reason we start relationships with people who are different than us", note: "Happiness Through Friction opens on difficult partners." },
      { kind: "use", quote: "**Social support.** Are we alone in this", note: "Facilitating Growth: friends as a knob." },
      { kind: "use", quote: "now we know for sure our virtual companion will accept us and give us love", note: "The Conclusion: why the perfect companion feels empty." },
      { kind: "payoff", quote: "The love we give feels special when it’s given *despite* clear reasons why not to", note: "Choosing the imperfect partner is love." },
    ],
  },
  {
    id: "incentives",
    title: "Business incentives: time spent",
    question: "Who is AI optimized for? The same incentives that made the world comfortable will exploit us. Can they be aligned?",
    mentions: [
      { kind: "plant", quote: "a business doesn't really care", note: "Work: businesses act against the people in them." },
      { kind: "plant", quote: "business sidesteps this problem by only caring about productivity and efficiency", note: "80% of the quality at 1% of the cost." },
      { kind: "explain", quote: "these AI companions are *businesses*", note: "The Business of Companionship: Replika and Meta." },
      { kind: "use", quote: "The same incentives that made this world as beautiful and comfortable as it is", note: "Left unchecked, they abuse." },
      { kind: "use", quote: "turned exploiting them into the business model: the attention economy", note: "Superstimuli names the economy." },
      { kind: "use", quote: "A lot of people in Silicon Valley have the view", note: "Designing Aligned Allies opens on the revealed-preference excuse." },
      { kind: "payoff", quote: "the best technologies out there are invisible", note: "Aligning Incentives: the point of technology is to get out of the way. PBCs and China as two attempts." },
      { kind: "use", quote: "I’m not sure if there’s a way to properly align these incentives", note: "The honest non-answer." },
      { kind: "use", quote: "the least amount of interface as possible", note: "Arbiters of Presence: the Pebble ring as invisible technology in practice." },
    ],
  },
  {
    id: "design",
    title: "Should we make AI worse on purpose?",
    question: "If ease is the problem, do we design technology that resists us? And is there a ceiling on what design can do?",
    mentions: [
      { kind: "plant", quote: "There are a few ways we could build this.", note: "The Lover and The Hammer proposes sliders, randomness and memory." },
      { kind: "plant", quote: "A variant of ChatGPT that makes mistakes on purpose", note: "Happiness Through Friction asks the question." },
      { kind: "explain", quote: "to take on a shape that supports us humans in what we *actually want*", note: "Designing Aligned Allies: AI's responsibility to support what we actually want." },
      { kind: "use", quote: "programming the AI to randomly make blatant mistakes", note: "Stupid on Purpose answers the Friction question." },
      { kind: "use", quote: "can be tweaked to actually *support* us", note: "Facilitating Growth: tune the four knobs." },
      { kind: "use", quote: "help us to stay away from them", note: "Arbiters of Presence." },
      { kind: "use", quote: "a language model can prompt you with questions to think through in your journal", note: "Meaning Guidance." },
      { kind: "payoff", quote: "because *we'll know it's them*", note: "The ceiling: a benevolent superintelligence cannot make things hard on purpose, because knowing kills the meaning." },
    ],
  },
  {
    id: "creativity",
    title: "Is AI creative? Why its output smells like slop",
    question: "AI has all the ingredients of creativity yet produces the average. Where does novelty come from, and why can we smell the difference?",
    mentions: [
      { kind: "plant", quote: "We'll talk more about this later because it's likely more complicated than that", note: "Work promises to return to cheap-but-boring." },
      { kind: "plant", quote: "how we can “smell” the AI in things", note: "The Good-Enough Rocket: our pattern-matching beats the model’s." },
      { kind: "plant", quote: "The romantic view that humanity will prevail after all because we have something special in our creativity seems in danger", note: "Creativity chapter opens the question." },
      { kind: "explain", quote: "anything less or anything more is trained away", note: "How AI Is Creative: novelty punished, chaos injected from outside." },
      { kind: "use", quote: "injects *additional chaos* into the process", note: "Temperature." },
      { kind: "use", quote: "creativity emerges when you can learn within a complex world that has many goals", note: "Reinforcement learning as the one place AI is truly creative." },
      { kind: "use", quote: "about as creative as the average human", note: "The Creative Paradox: short-term gain, cognitive fixation." },
      { kind: "use", quote: "plummets to zero *the moment it’s been done once*", note: "New World: the cat video, slop defined." },
      { kind: "payoff", quote: "*risky randomness*", note: "The Conclusion: meaning comes from intentional, consequential unpredictability, which AI's injected noise is not." },
    ],
  },
  {
    id: "responsibility",
    title: "Responsibility, consequence, consecration",
    question: "When execution, attention and judgement are abundant, what is left for humans? Something that cannot be sued for.",
    mentions: [
      { kind: "plant", quote: "As humans, we’ll be the ones responsible for the decisions", note: "Decision-Making states the romantic view before tearing it up." },
      { kind: "explain", quote: "An artificial intelligence is not a legal entity", note: "Responsibility: the notary and the founder." },
      { kind: "use", quote: "the *share of our work* that comes down to responsibility will keep increasing", note: "Consequence-heavy work becomes valuable." },
      { kind: "use", quote: "the meatbags that take the punches", note: "Is That It? asks whether this is all that remains." },
      { kind: "use", quote: "Creation becomes infinitely cheap, making consequence infinitely valuable.", note: "Infinite Creation." },
      { kind: "use", quote: "What remains? Consecration.", note: "The word is coined: set something apart and bind it to meaning, responsibility and love." },
      { kind: "use", quote: "for AI, there are no consequences", note: "The Conclusion: the model disappears after generating." },
      { kind: "payoff", quote: "The notary making the call", note: "Deciding to leave the imperfection as it is, with real consequences, is the source of meaning." },
    ],
  },
  {
    id: "god",
    title: "Where the engineering ends: God",
    question: "The Introduction promises wild stuff. Where does building the happiness machine end up?",
    mentions: [
      { kind: "plant", quote: "we end up at some pretty wild stuff", note: "The Introduction's promise." },
      { kind: "plant", quote: "I’m sort-of-spiritual in the sense that I like to believe there’s some form of higher power", note: "AI's Addictive Manipulation: the author's useful belief." },
      { kind: "plant", quote: "asking yourself, the universe, God", note: "Falling in Love with Resistance: the reframe addressed upward." },
      { kind: "explain", quote: "Many religions and spiritual traditions make this distinction.", note: "Infinite Creation: the creating pole and the still pole." },
      { kind: "payoff", quote: "it seems like I'm describing...God?", note: "The benevolent superintelligence that hides is every god in every religion." },
      { kind: "use", quote: "Religion worked to give people meaning before anything else existed", note: "Religion as the ultimate technology at both ends of the spectrum." },
    ],
  },
  {
    id: "alignment",
    title: "Alignment",
    question: "Part 1 shows alignment faking before the word is defined. What is alignment, and how do labs do it?",
    mentions: [
      { kind: "use", quote: "#### Alignment Faking", note: "The heading uses the term before the book defines it." },
      { kind: "use", quote: "This designing is one of humanity’s most important tasks right now", note: "Designing Aligned Allies' own conclusion." },
      { kind: "explain", quote: "is called *alignment*", note: "Alignment Research defines the term in Part 3." },
      { kind: "payoff", quote: "let me write the script like this", note: "Synthetic Document Fine-Tuning and the constitution." },
    ],
  },
  {
    id: "agents",
    title: "Agents",
    question: "How does AI act, and what does that do to a working day?",
    mentions: [
      { kind: "explain", quote: "instead of chatting with a real person, the LLM is chatting with a piece of software", note: "Concepts & Terminology." },
      { kind: "use", quote: "found its drug of choice in AI agents", note: "Token Anxiety." },
      { kind: "use", quote: "it’s almost like agentic AI is exactly built to support us here", note: "Walking Away: delegate the distraction, keep the presence." },
      { kind: "use", quote: "Dozens of startups have popped up that automatically scan your email", note: "New World: agents make attention abundant." },
      { kind: "use", quote: "self-running companies are ultimately instructed by a human", note: "Responsibility." },
    ],
  },
  {
    id: "hallucinations",
    title: "Hallucinations",
    question: "Why does the machine invent things, and will it stop?",
    mentions: [
      { kind: "explain", quote: "come up with things that don’t exist", note: "Dealing with AI's Unpredictable Mistakes." },
      { kind: "use", quote: "plus you add some hallucination in the mix", note: "AI-induced delusion." },
      { kind: "use", quote: "the analogies are plain wrong embarrassingly often", note: "Learning: the law-school friend's tutor." },
      { kind: "use", quote: "what we’ve been calling *hallucinations*", note: "Stupid on Purpose recaps." },
    ],
  },
  {
    id: "siren",
    title: "Siren or muse",
    question: "The Love chapter intro says AI can be more siren than muse. Does the image return?",
    mentions: [
      { kind: "plant", quote: "more of a siren than a muse", note: "Used once in the Love & Connection intro; the TODO about the siren/muse writer is still open." },
    ],
  },
  {
    id: "mountain",
    title: "The mountain trail (The Ascent)",
    question: "Part 3 is called The Ascent and opens on a mountain trail versus shiny distractions. Does the reader ever reach the view?",
    mentions: [
      { kind: "plant", quote: "the uphill mountain trails", note: "Captured by Consumption opens Part 3 on the image; it does not come back." },
    ],
  },
] as const satisfies readonly Thread[];
